/**
 * RemediationAdvisor 修复方案顾问服务
 * 生成可执行的修复方案和回滚方案
 *
 * 设备无关设计：修复步骤以操作意图（operation intent）描述，
 * 实际命令由设备驱动（DeviceDriver）根据目标设备类型生成和执行。
 *
 * Requirements: 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, A7.28, A7.29
 * - 7.1: 识别根因后生成分步修复方案
 * - 7.2: 修复步骤包含设备无关的操作意图描述
 * - 7.3: 修复步骤包含验证方法
 * - 7.4: 生成对应的回滚方案
 * - 7.5: 标记步骤是否可自动执行
 * - 7.6: 评估每个步骤的风险级别
 * - 7.7: 估算完整修复方案的预计时间
 * - 7.8: 关键配置变更需要手动确认
 * - A7.28: 修复建议设备无关化
 * - A7.29: 脚本合成泛化
 */

import fs from 'fs/promises';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import {
  RootCauseAnalysis,
  RemediationPlan,
  RemediationStep,
  RollbackStep,
  ExecutionResult,
  RiskLevel,
  IRemediationAdvisor,
  StepVerification,
  OperationalRule,
} from '../../types/ai-ops';
import { logger } from '../../utils/logger';
import { getServiceAsync, SERVICE_NAMES } from '../bootstrap';
import { DevicePool } from '../device/devicePool';
import { deviceDriverManager } from '../device/deviceDriverManager';
import type { DeviceDriver, DeviceExecutionResult } from '../../types/device-driver';
import { aiAnalyzer } from './aiAnalyzer';
import { auditLogger } from './auditLogger';
import { configSnapshotService } from './configSnapshotService';
import { knowledgeBase, ragEngine } from './rag';
import { ruleEvolutionService } from './ruleEvolutionService';

const DATA_DIR = path.join(process.cwd(), 'data', 'ai-ops');
const REMEDIATION_DIR = path.join(DATA_DIR, 'remediations');
const PLANS_DIR = path.join(REMEDIATION_DIR, 'plans');
const EXECUTIONS_DIR = path.join(REMEDIATION_DIR, 'executions');

/**
 * Critical operation categories that require manual confirmation
 * Requirement 7.8: 关键配置变更需要手动确认
 *
 * NOTE: These are device-agnostic operation intent patterns.
 * Actual command validation is delegated to the device driver.
 */
const CRITICAL_OPERATION_PATTERNS = [
  /user/i,
  /password/i,
  /identity/i,
  /firewall.*filter/i,
  /firewall.*nat/i,
  /ipv6.*firewall/i,
  /routing/i,
  /certificate/i,
  /reset/i,
  /reboot/i,
  /interface.*disable/i,
  /shutdown/i,
  /factory.?reset/i,
  /firmware.*upgrade/i,
];

/**
 * Remediation templates for common root causes
 *
 * NOTE: `command` fields contain device-agnostic operation intent descriptions.
 * Actual device-specific commands are generated by the device driver at execution time.
 * The intent format is: "action_type:category/operation [parameters]"
 */
interface RemediationTemplate {
  rootCausePattern: RegExp;
  category: string;
  steps: Array<{
    description: string;
    /** Device-agnostic operation intent — actual commands generated by device driver */
    command: string;
    verification: StepVerification;
    riskLevel: RiskLevel;
    estimatedDuration: number;
  }>;
  rollback: Array<{
    description: string;
    command: string;
    condition?: string;
  }>;
}

const REMEDIATION_TEMPLATES: RemediationTemplate[] = [
  {
    rootCausePattern: /high.*cpu|cpu.*high|cpu.*usage/i,
    category: 'system',
    steps: [
      {
        description: '检查当前 CPU 使用情况',
        command: 'query:system/resource',
        verification: {
          command: 'query:system/resource',
          expectedResult: 'CPU 使用率应显示当前值',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查高 CPU 占用的进程',
        command: 'query:system/processes',
        verification: {
          command: 'query:system/processes',
          expectedResult: '显示进程 CPU 占用列表',
        },
        riskLevel: 'low',
        estimatedDuration: 10,
      },
      {
        description: '检查连接跟踪表大小',
        command: 'query:firewall/connections count-only',
        verification: {
          command: 'query:firewall/connections count-only',
          expectedResult: '连接数应在合理范围内',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
    ],
    rollback: [
      {
        description: '无需回滚（仅诊断操作）',
        command: '# 诊断操作无需回滚',
      },
    ],
  },
  {
    rootCausePattern: /memory.*exhaustion|memory.*high|out of memory|oom/i,
    category: 'system',
    steps: [
      {
        description: '检查当前内存使用情况',
        command: 'query:system/resource',
        verification: {
          command: 'query:system/resource',
          expectedResult: '显示内存使用统计',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '清理 DNS 缓存',
        command: 'execute:dns/cache-flush',
        verification: {
          command: 'query:dns/cache count-only',
          expectedResult: 'DNS 缓存条目数应减少',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查并清理过期的连接跟踪',
        command: 'execute:firewall/connections-cleanup expired',
        verification: {
          command: 'query:firewall/connections count-only',
          expectedResult: '连接数应减少',
        },
        riskLevel: 'medium',
        estimatedDuration: 10,
      },
    ],
    rollback: [
      {
        description: '连接跟踪会自动重建',
        command: '# 连接跟踪会根据流量自动重建',
      },
    ],
  },
  {
    rootCausePattern: /disk.*full|disk.*space|storage/i,
    category: 'system',
    steps: [
      {
        description: '检查磁盘使用情况',
        command: 'query:system/resource',
        verification: {
          command: 'query:system/resource',
          expectedResult: '显示磁盘使用统计',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '列出文件占用情况',
        command: 'query:system/files',
        verification: {
          command: 'query:system/files',
          expectedResult: '显示文件列表',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '清理旧的备份文件',
        command: 'execute:system/files-cleanup backup older-than=7d',
        verification: {
          command: 'query:system/files filter=backup',
          expectedResult: '旧备份文件应被删除',
        },
        riskLevel: 'medium',
        estimatedDuration: 10,
      },
    ],
    rollback: [
      {
        description: '备份文件删除后无法恢复',
        command: '# 建议在删除前先下载重要备份',
      },
    ],
  },
  {
    rootCausePattern: /interface.*down|link.*down|disconnected/i,
    category: 'interface',
    steps: [
      {
        description: '检查接口状态',
        command: 'query:interface/list',
        verification: {
          command: 'query:interface/list',
          expectedResult: '显示接口状态列表',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '尝试重新启用接口',
        command: 'execute:interface/enable filter=not-running',
        verification: {
          command: 'query:interface/list filter=running',
          expectedResult: '接口应恢复运行状态',
        },
        riskLevel: 'medium',
        estimatedDuration: 15,
      },
    ],
    rollback: [
      {
        description: '如需禁用接口',
        command: 'execute:interface/disable name=<interface_name>',
        condition: '仅在需要时执行',
      },
    ],
  },
  {
    rootCausePattern: /interface.*flapping|状态变化|state change/i,
    category: 'interface',
    steps: [
      {
        description: '检查接口状态历史',
        command: 'query:log/filter topic=interface',
        verification: {
          command: 'query:log/filter topic=interface',
          expectedResult: '显示接口状态变化日志',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查接口配置',
        command: 'query:interface/ethernet',
        verification: {
          command: 'query:interface/ethernet',
          expectedResult: '显示以太网接口配置',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '调整接口速率和双工模式为自动协商',
        command: 'configure:interface/ethernet speed=auto',
        verification: {
          command: 'query:interface/ethernet',
          expectedResult: '速率应设置为 auto',
        },
        riskLevel: 'medium',
        estimatedDuration: 10,
      },
    ],
    rollback: [
      {
        description: '恢复原始速率设置',
        command: 'configure:interface/ethernet speed=<original_speed>',
        condition: '如果自动协商导致问题',
      },
    ],
  },
  {
    rootCausePattern: /auth.*fail|login.*fail|password|credential/i,
    category: 'security',
    steps: [
      {
        description: '检查登录失败日志',
        command: 'query:log/filter topic=system keyword=login',
        verification: {
          command: 'query:log/filter topic=system keyword=login',
          expectedResult: '显示登录相关日志',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查用户列表',
        command: 'query:user/list',
        verification: {
          command: 'query:user/list',
          expectedResult: '显示用户列表',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查防火墙是否有 IP 封禁',
        command: 'query:firewall/address-list filter=blacklist',
        verification: {
          command: 'query:firewall/address-list filter=blacklist',
          expectedResult: '显示黑名单 IP',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
    ],
    rollback: [
      {
        description: '无需回滚（仅诊断操作）',
        command: '# 诊断操作无需回滚',
      },
    ],
  },
  {
    rootCausePattern: /firewall.*block|drop|reject|deny/i,
    category: 'security',
    steps: [
      {
        description: '检查防火墙规则',
        command: 'query:firewall/filter-rules',
        verification: {
          command: 'query:firewall/filter-rules',
          expectedResult: '显示防火墙过滤规则',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查 NAT 规则',
        command: 'query:firewall/nat-rules',
        verification: {
          command: 'query:firewall/nat-rules',
          expectedResult: '显示 NAT 规则',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查连接跟踪',
        command: 'query:firewall/connections',
        verification: {
          command: 'query:firewall/connections',
          expectedResult: '显示活动连接',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
    ],
    rollback: [
      {
        description: '无需回滚（仅诊断操作）',
        command: '# 诊断操作无需回滚',
      },
    ],
  },
  {
    rootCausePattern: /timeout|connection.*lost|unreachable/i,
    category: 'network',
    steps: [
      {
        description: '检查路由表',
        command: 'query:routing/table',
        verification: {
          command: 'query:routing/table',
          expectedResult: '显示路由表',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查 ARP 表',
        command: 'query:arp/table',
        verification: {
          command: 'query:arp/table',
          expectedResult: '显示 ARP 表',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '测试网关连通性',
        command: 'execute:diagnostic/ping target=8.8.8.8 count=3',
        verification: {
          command: 'execute:diagnostic/ping target=8.8.8.8 count=1',
          expectedResult: '应收到 ping 响应',
        },
        riskLevel: 'low',
        estimatedDuration: 10,
      },
    ],
    rollback: [
      {
        description: '无需回滚（仅诊断操作）',
        command: '# 诊断操作无需回滚',
      },
    ],
  },
  {
    rootCausePattern: /traffic.*spike|bandwidth|throughput|流量/i,
    category: 'network',
    steps: [
      {
        description: '检查接口流量统计',
        command: 'query:interface/stats',
        verification: {
          command: 'query:interface/stats',
          expectedResult: '显示接口流量统计',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查活动连接',
        command: 'query:firewall/connections',
        verification: {
          command: 'query:firewall/connections count-only',
          expectedResult: '显示连接数',
        },
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      {
        description: '检查实时流量分布',
        command: 'execute:diagnostic/traffic-monitor interface=all',
        verification: {
          command: 'execute:diagnostic/traffic-monitor interface=all',
          expectedResult: '显示实时流量分布',
        },
        riskLevel: 'low',
        estimatedDuration: 15,
      },
    ],
    rollback: [
      {
        description: '无需回滚（仅诊断操作）',
        command: '# 诊断操作无需回滚',
      },
    ],
  },
];

/**
 * Get date string (YYYY-MM-DD)
 */
function getDateString(timestamp: number): string {
  const date = new Date(timestamp);
  return date.toISOString().split('T')[0];
}

export class RemediationAdvisor implements IRemediationAdvisor {
  private initialized = false;
  private plansCache: Map<string, RemediationPlan> = new Map();
  private executionHistory: Map<string, ExecutionResult[]> = new Map();

  // 缓存清理定时器
  private cacheCleanupTimer: NodeJS.Timeout | null = null;

  // 最大缓存条目数
  private readonly MAX_PLANS_CACHE_SIZE = 200;
  private readonly MAX_EXECUTION_HISTORY_SIZE = 100;

  // 缓存 TTL（24 小时）
  private readonly CACHE_TTL_MS = 24 * 60 * 60 * 1000;

  // Pending 状态计划最大存活时间（1 小时）
  // Requirements: 6.2 - pending 状态计划清理
  private readonly PENDING_MAX_AGE_MS = 60 * 60 * 1000;

  /**
   * Ensure data directories exist
   */
  private async ensureDataDirs(): Promise<void> {
    try {
      await fs.mkdir(PLANS_DIR, { recursive: true });
      await fs.mkdir(EXECUTIONS_DIR, { recursive: true });
    } catch (error) {
      logger.error('Failed to create remediation directories:', error);
    }
  }

  /**
   * Initialize service
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;
    await this.ensureDataDirs();
    await this.loadPlans();

    // 初始化规则进化服务
    await ruleEvolutionService.initialize();

    // 启动缓存清理定时器
    this.startCacheCleanupTimer();

    this.initialized = true;
    logger.info('RemediationAdvisor initialized');
  }

  /**
   * 启动缓存清理定时器
   */
  private startCacheCleanupTimer(): void {
    if (this.cacheCleanupTimer) {
      clearInterval(this.cacheCleanupTimer);
    }

    // 每 30 分钟清理一次过期缓存
    const CLEANUP_INTERVAL_MS = 30 * 60 * 1000;
    this.cacheCleanupTimer = setInterval(() => {
      this.cleanupExpiredCache();
    }, CLEANUP_INTERVAL_MS);

    logger.debug('RemediationAdvisor cache cleanup timer started');
  }

  /**
   * 停止缓存清理定时器
   */
  stopCleanupTimer(): void {
    if (this.cacheCleanupTimer) {
      clearInterval(this.cacheCleanupTimer);
      this.cacheCleanupTimer = null;
      logger.debug('RemediationAdvisor cache cleanup timer stopped');
    }
  }

  /**
   * 清理过期缓存
   * Requirements: 6.1, 6.3, 6.4 - pending 状态计划清理
   */
  private cleanupExpiredCache(): void {
    const now = Date.now();
    let cleanedPlans = 0;
    let cleanedHistory = 0;
    let expiredPendingPlans = 0;

    // Requirements: 6.1, 6.3 - 清理过期的 pending 状态计划
    for (const [id, plan] of this.plansCache) {
      if (plan.status === 'pending') {
        if (now - plan.timestamp > this.PENDING_MAX_AGE_MS) {
          // 将过期的 pending 计划状态更新为 expired
          plan.status = 'expired' as RemediationPlan['status'];
          this.plansCache.set(id, plan);
          expiredPendingPlans++;
          // Requirements: 6.4 - 记录清理日志
          logger.info(`Expired pending remediation plan: ${id}, age: ${Math.round((now - plan.timestamp) / 1000 / 60)} minutes`);
        }
      }
    }

    // 清理过期的计划缓存（只清理已完成、失败或过期的计划）
    for (const [id, plan] of this.plansCache) {
      if (plan.status !== 'pending' && plan.status !== 'in_progress') {
        if (now - plan.timestamp > this.CACHE_TTL_MS) {
          this.plansCache.delete(id);
          cleanedPlans++;
        }
      }
    }

    // 如果缓存仍然过大，删除最旧的已完成计划
    if (this.plansCache.size > this.MAX_PLANS_CACHE_SIZE) {
      const completedPlans = Array.from(this.plansCache.entries())
        .filter(([, plan]) => plan.status !== 'pending' && plan.status !== 'in_progress')
        .sort((a, b) => a[1].timestamp - b[1].timestamp);

      const toRemove = completedPlans.slice(0, this.plansCache.size - this.MAX_PLANS_CACHE_SIZE);
      for (const [id] of toRemove) {
        this.plansCache.delete(id);
        cleanedPlans++;
      }
    }

    // 清理执行历史（保留最近的）
    if (this.executionHistory.size > this.MAX_EXECUTION_HISTORY_SIZE) {
      const entries = Array.from(this.executionHistory.keys());
      const toRemove = entries.slice(0, this.executionHistory.size - this.MAX_EXECUTION_HISTORY_SIZE);
      for (const id of toRemove) {
        this.executionHistory.delete(id);
        cleanedHistory++;
      }
    }

    if (cleanedPlans > 0 || cleanedHistory > 0 || expiredPendingPlans > 0) {
      logger.info(`RemediationAdvisor cleaned up ${cleanedPlans} plans, ${cleanedHistory} history entries, ${expiredPendingPlans} expired pending plans`);
    }
  }

  /**
   * Load existing plans from disk
   */
  private async loadPlans(): Promise<void> {
    try {
      const files = await fs.readdir(PLANS_DIR);
      for (const file of files) {
        if (file.endsWith('.json')) {
          try {
            const content = await fs.readFile(path.join(PLANS_DIR, file), 'utf-8');
            const plan = JSON.parse(content) as RemediationPlan;
            this.plansCache.set(plan.id, plan);
          } catch (error) {
            logger.warn(`Failed to load plan file ${file}:`, error);
          }
        }
      }
      logger.info(`Loaded ${this.plansCache.size} remediation plans`);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        logger.error('Failed to load plans:', error);
      }
    }
  }

  /**
   * Save plan to disk
   */
  private async savePlan(plan: RemediationPlan): Promise<void> {
    await this.ensureDataDirs();
    const filePath = path.join(PLANS_DIR, `${plan.id}.json`);
    await fs.writeFile(filePath, JSON.stringify(plan, null, 2), 'utf-8');
    this.plansCache.set(plan.id, plan);
  }

  /**
   * Save execution results to disk
   */
  private async saveExecutionResults(planId: string, results: ExecutionResult[]): Promise<void> {
    await this.ensureDataDirs();
    const dateStr = getDateString(Date.now());
    const filePath = path.join(EXECUTIONS_DIR, `${dateStr}.json`);

    let executions: Array<{ planId: string; timestamp: number; results: ExecutionResult[] }> = [];
    try {
      const content = await fs.readFile(filePath, 'utf-8');
      executions = JSON.parse(content);
    } catch {
      // File doesn't exist, start fresh
    }

    executions.push({
      planId,
      timestamp: Date.now(),
      results,
    });

    await fs.writeFile(filePath, JSON.stringify(executions, null, 2), 'utf-8');
    this.executionHistory.set(planId, results);
  }

  /**
   * Try to index a completed remediation plan to the knowledge base
   * Requirements: 7.1-7.4, 8.1-8.3
   * - 7.1: 状态更新为 completed 时调用索引
   * - 7.2: 所有步骤执行成功后索引
   * - 7.3: 执行完最后一步后检查并索引
   * - 7.4: 索引失败时记录警告但不抛出错误
   * - 8.1: 已索引的方案跳过重复索引
   * - 8.2: 使用 indexed 标志跟踪索引状态
   * - 8.3: 索引前检查 indexed 标志
   */
  private async tryIndexPlan(plan: RemediationPlan): Promise<void> {
    // Requirement 8.1, 8.3: 检查是否已索引，避免重复索引
    if (plan.indexed) {
      logger.debug(`Plan ${plan.id} already indexed, skipping`);
      return;
    }

    // 检查状态是否为 completed
    if (plan.status !== 'completed') {
      logger.debug(`Plan ${plan.id} status is ${plan.status}, not indexing`);
      return;
    }

    // 收集执行结果
    const results = await this.getExecutionHistory(plan.id);
    if (results.length === 0) {
      logger.debug(`No execution results for plan ${plan.id}, skipping indexing`);
      return;
    }

    try {
      // Requirement 7.1-7.3: 调用 indexRemediation 索引到知识库
      await knowledgeBase.indexRemediation(plan, results);

      // Requirement 8.2: 索引成功后设置 indexed = true
      plan.indexed = true;
      await this.savePlan(plan);

      logger.info(`Remediation plan indexed to knowledge base: ${plan.id}`);
    } catch (error) {
      // Requirement 7.4: 索引失败时记录警告但不抛出错误
      logger.warn(`Failed to index remediation plan ${plan.id}`, { error });
      // 不抛出错误，避免影响主流程
    }
  }


  /**
   * Generate remediation plan based on root cause analysis
   * Requirements: 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8
   */
  async generatePlan(analysis: RootCauseAnalysis): Promise<RemediationPlan> {
    await this.initialize();

    const planId = uuidv4();
    const now = Date.now();

    // Find the primary root cause (highest confidence)
    const primaryRootCause = analysis.rootCauses.length > 0
      ? analysis.rootCauses.reduce((a, b) => a.confidence > b.confidence ? a : b)
      : null;

    if (!primaryRootCause) {
      // Return empty plan if no root cause identified
      const emptyPlan: RemediationPlan = {
        id: planId,
        alertId: analysis.alertId,
        rootCauseId: '',
        timestamp: now,
        steps: [],
        rollback: [],
        overallRisk: 'low',
        estimatedDuration: 0,
        requiresConfirmation: false,
        status: 'pending',
        matchedFaultPatternId: analysis.matchedFaultPatternId,
      };
      await this.savePlan(emptyPlan);
      return emptyPlan;
    }

    // Step 0: Try RAG-enhanced remediation generation (Requirements: 7.1 - 使用 RAG 增强修复方案生成)
    let steps: RemediationStep[] = [];
    let rollback: RollbackStep[] = [];
    let ragEnhanced = false;

    try {
      const ragPlan = await ragEngine.generateRemediation(analysis);
      // EnhancedRemediationPlan has a 'plan' property containing the actual RemediationPlan
      if (ragPlan && ragPlan.plan && ragPlan.plan.steps && ragPlan.plan.steps.length > 0) {
        steps = ragPlan.plan.steps.map((s: RemediationStep, index: number) => ({
          order: index + 1,
          description: s.description,
          command: s.command,
          verification: s.verification || {
            command: 'query:system/resource',
            expectedResult: '验证操作结果',
          },
          autoExecutable: this.isAutoExecutable(s.command, s.riskLevel || 'medium'),
          riskLevel: s.riskLevel || 'medium',
          estimatedDuration: s.estimatedDuration || 10,
        }));

        rollback = (ragPlan.plan.rollback || []).map((r: RollbackStep, index: number) => ({
          order: index + 1,
          description: r.description,
          command: r.command,
          condition: r.condition,
        }));

        ragEnhanced = true;
        logger.info(`RAG-enhanced remediation plan generated with ${steps.length} steps`);
      }
    } catch (error) {
      logger.debug('RAG remediation generation failed, falling back to template/AI:', error);
    }

    // Step 1: Try to match a template (if RAG didn't provide a plan)
    let templateMatched = false;
    if (!ragEnhanced) {
      for (const template of REMEDIATION_TEMPLATES) {
        if (template.rootCausePattern.test(primaryRootCause.description)) {
          steps = template.steps.map((s, index) => ({
            order: index + 1,
            description: s.description,
            command: s.command,
            verification: s.verification,
            autoExecutable: this.isAutoExecutable(s.command, s.riskLevel),
            riskLevel: s.riskLevel,
            estimatedDuration: s.estimatedDuration,
          }));

          rollback = template.rollback.map((r, index) => ({
            order: index + 1,
            description: r.description,
            command: r.command,
            condition: r.condition,
          }));

          templateMatched = true;
          logger.info(`Matched remediation template for category: ${template.category}`);
          break;
        }
      }
    }

    // Step 2: If no template matched and no RAG plan, try AI-generated plan
    if (!ragEnhanced && !templateMatched) {
      try {
        const aiPlan = await this.generateAIPlan(analysis, primaryRootCause);
        steps = aiPlan.steps;
        rollback = aiPlan.rollback;
      } catch (error) {
        logger.warn('AI plan generation failed, using generic diagnostic plan:', error);
        // Fallback to generic diagnostic plan
        steps = this.getGenericDiagnosticSteps();
        rollback = [{
          order: 1,
          description: '无需回滚（仅诊断操作）',
          command: '# 诊断操作无需回滚',
        }];
      }
    }

    // Step 3: Calculate overall risk and duration
    const overallRisk = this.calculateOverallRisk(steps);
    const estimatedDuration = steps.reduce((sum, s) => sum + s.estimatedDuration, 0);

    // Step 4: Determine if confirmation is required
    // Requirement 7.8: 关键配置变更需要手动确认
    const requiresConfirmation = steps.some(s =>
      s.riskLevel === 'high' || !s.autoExecutable
    );

    const plan: RemediationPlan = {
      id: planId,
      alertId: analysis.alertId,
      rootCauseId: primaryRootCause.id,
      timestamp: now,
      steps,
      rollback,
      overallRisk,
      estimatedDuration,
      requiresConfirmation,
      status: 'pending',
      tenantId: analysis.tenantId,
      deviceId: analysis.deviceId,
      description: `Remediation for: ${primaryRootCause.description}`,
    };

    // Save plan
    await this.savePlan(plan);

    // Log audit
    await auditLogger.log({
      tenantId: plan.tenantId,
      deviceId: plan.deviceId,
      action: 'remediation_execute',
      actor: 'system',
      details: {
        trigger: 'plan_generated',
        metadata: {
          planId: plan.id,
          alertId: analysis.alertId,
          rootCauseId: primaryRootCause.id,
          stepsCount: steps.length,
          overallRisk,
          estimatedDuration,
        },
      },
    });

    logger.info(`Generated remediation plan ${planId} with ${steps.length} steps, risk: ${overallRisk}`);
    return plan;
  }

  /**
   * Generate AI-based remediation plan
   */
  private async generateAIPlan(
    analysis: RootCauseAnalysis,
    rootCause: { id: string; description: string; confidence: number }
  ): Promise<{ steps: RemediationStep[]; rollback: RollbackStep[] }> {

    // 获取适用的操作规则 (Requirements: Phase 2)
    let rules: OperationalRule[] = [];
    try {
      const results = await ruleEvolutionService.findApplicableRules(rootCause.description);
      rules = results.map(r => r.rule);
      if (rules.length > 0) {
        logger.info(`Found ${rules.length} applicable rules for AI plan generation`);
      }
    } catch (error) {
      logger.warn('Failed to fetch rules for AI plan generation', error);
    }

    const result = await aiAnalyzer.analyze({
      type: 'alert',
      context: {
        alertEvent: {
          id: analysis.alertId,
          ruleId: 'remediation',
          ruleName: 'Remediation Plan Generation',
          severity: 'warning',
          metric: 'remediation',
          currentValue: 0,
          threshold: 0,
          message: `Generate remediation plan for: ${rootCause.description}`,
          status: 'active',
          triggeredAt: analysis.timestamp,
        },
        systemMetrics: {
          cpu: { usage: 0 },
          memory: { total: 0, used: 0, free: 0, usage: 0 },
          disk: { total: 0, used: 0, free: 0, usage: 0 },
          uptime: 0,
        },
        analysisType: 'remediation',
        rootCause: rootCause.description,
        impact: analysis.impact,
        operationalRules: rules.map(r => `[${r.type.toUpperCase()}] ${r.description} (Source: ${r.source.type})`),
      },
    });

    // Parse AI recommendations into steps
    let steps: RemediationStep[] = (result.recommendations || []).map((rec, index) => {
      // Try to extract command from recommendation
      const commandMatch = rec.match(/`([^`]+)`/) || rec.match(/命令[：:]\s*(.+)/);
      const command = commandMatch ? commandMatch[1] : `query:system/resource`;

      return {
        order: index + 1,
        description: rec.replace(/`[^`]+`/g, '').trim(),
        command,
        verification: {
          command: 'query:system/resource',
          expectedResult: '验证操作结果',
        },
        autoExecutable: this.isAutoExecutable(command, result.riskLevel || 'medium'),
        riskLevel: result.riskLevel || 'medium',
        estimatedDuration: 10,
      };
    });

    // If no steps generated, use generic diagnostic
    if (steps.length === 0) {
      steps = this.getGenericDiagnosticSteps();
    }

    // Check for auto-response configuration (Requirements: System Association Issue #2)
    if (analysis.autoResponseConfig && analysis.autoResponseConfig.enabled) {
      steps.unshift({
        order: 0, // Will be reordered
        description: '执行自动响应脚本 (Auto-Response)',
        command: analysis.autoResponseConfig.script,
        verification: {
          command: 'query:log/filter topic=script',
          expectedResult: '脚本执行日志',
        },
        autoExecutable: true,
        riskLevel: 'medium',
        estimatedDuration: 5,
      });

      // Re-order steps
      steps.forEach((s, i) => s.order = i + 1);
    }

    return {
      steps,
      rollback: [{
        order: 1,
        description: '如需回滚，请恢复之前的配置快照',
        command: '# 使用配置快照恢复',
        condition: '仅在修改导致问题时执行',
      }],
    };
  }


  /**
   * Get generic diagnostic steps
   */
  private getGenericDiagnosticSteps(): RemediationStep[] {
    return [
      {
        order: 1,
        description: '检查系统资源状态',
        command: 'query:system/resource',
        verification: {
          command: 'query:system/resource',
          expectedResult: '显示系统资源信息',
        },
        autoExecutable: true,
        riskLevel: 'low',
        estimatedDuration: 5,
      },
      // Step 2: Auto-Response (Requirements: System Association Issue #2)
      // Check if event has auto-response configuration and inject it as the first step
      // Note: analysis.alertId is used to retrieve the event, but we need the event object itself.
      // Since we don't have the full event object here, we rely on the fact that the caller
      // (AlertPipeline) should have passed the event context or we need to look it up.
      // However, for this fix scope, we will assume the analysis metadata might contain it
      // or we fetch it. *Better approach*: modify generatePlan signature to accept event?
      // Current signature: generatePlan(analysis: RootCauseAnalysis)
      // We can't easily change the signature without affecting other callers.
      // Alternative: The `RootCauseAnalysis` should contain the autoResponseConfig.
      // Let's check `RootCauseAnalysis` definition in `ai-ops.ts`.
      // It doesn't.

      // *Correction*: We need to fetch the event to get the config, OR relying on the template matching.
      // But the requirement is to use the rule's specific auto-response script.

      // Let's try to fetch the event from AlertEngine active alerts if possible, or
      // we assume the event details are not readily available in `analysis`.

      // WAIT. THe user requirement is: "AlertEvent enters pipeline with config... RemediationAdvisor generates plan using it".
      // `RemediationAdvisor.generatePlan` takes `RootCauseAnalysis`.
      // `AlertPipeline` calls `aiAnalyzer.analyze` -> `RootCauseAnalysis`.
      // `AlertPipeline` calls `remediationAdvisor.generatePlan(analysis)`.

      // We need to pass the `autoResponseConfig` from `AlertEvent` to `RootCauseAnalysis` first.
      // Let's look at `AlertPipeline` -> `startAnalysis`.

      // Modification Plan Revised:
      // 1. AlertPipeline.ts: inject autoResponseConfig into RootCauseAnalysis result (or pass event to generatePlan).
      // Let's stick to modifying `RemediationAdvisor` to look up the event or modify `RootCauseAnalysis` type.

      // Let's modify `RootCauseAnalysis` in `ai-ops.ts` to include `autoResponseConfig`?
      // Yes, that makes sense.

      // Let's abort this edit and modify `RootCauseAnalysis` first.
      {
        order: 3,
        description: '检查接口状态',
        command: 'query:interface/list',
        verification: {
          command: 'query:interface/list',
          expectedResult: '显示接口列表',
        },
        autoExecutable: true,
        riskLevel: 'low',
        estimatedDuration: 5,
      },
    ];
  }

  /**
   * Check if a command/operation intent can be auto-executed
   * Requirement 7.5, 7.8: 标记步骤是否可自动执行，关键配置需手动确认
   *
   * NOTE: Checks device-agnostic operation intent patterns.
   * Actual command safety validation is delegated to the device driver.
   */
  private isAutoExecutable(command: string, riskLevel: RiskLevel): boolean {
    // High risk commands always require confirmation
    if (riskLevel === 'high') {
      return false;
    }

    // Check against critical operation patterns (device-agnostic)
    for (const pattern of CRITICAL_OPERATION_PATTERNS) {
      if (pattern.test(command)) {
        return false;
      }
    }

    // Read-only / query operations are auto-executable
    if (/^query:|\/print|\/monitor|diagnostic\/ping|diagnostic\/traceroute/i.test(command)) {
      return true;
    }

    // Medium risk commands require confirmation
    if (riskLevel === 'medium') {
      return false;
    }

    return true;
  }

  /**
   * Calculate overall risk level
   * Requirement 7.6: 评估每个步骤的风险级别
   */
  private calculateOverallRisk(steps: RemediationStep[]): RiskLevel {
    if (steps.length === 0) return 'low';

    const hasHigh = steps.some(s => s.riskLevel === 'high');
    const hasMedium = steps.some(s => s.riskLevel === 'medium');

    if (hasHigh) return 'high';
    if (hasMedium) return 'medium';
    return 'low';
  }

  /**
   * Execute a single step
   * Requirement 7.1: 执行修复步骤
   * Requirements: critic-reflector 12.1-12.5
   * - 12.1: 在步骤执行后调用 CriticService 评估（检查功能开关）
   * - 12.2: 将评估结果存储到 ExecutionResult.evaluation 字段
   * - 12.3: 将评估结果包含在执行历史中
   * - 12.4: 实现关键失败时停止执行
   */
  async executeStep(planId: string, stepOrder: number): Promise<ExecutionResult> {
    await this.initialize();

    const plan = await this.getPlan(planId);
    if (!plan) {
      throw new Error(`Plan not found: ${planId}`);
    }

    // Ensure deviceId is present for multi-device support
    if (!plan.deviceId) {
      logger.warn(`Plan ${planId} missing deviceId, attempting to use default/global context`);
    }

    const step = plan.steps.find(s => s.order === stepOrder);
    if (!step) {
      throw new Error(`Step ${stepOrder} not found in plan ${planId}`);
    }

    const startTime = Date.now();
    let result: ExecutionResult;

    try {
      // Create pre-execution snapshot for safety
      if (step.riskLevel !== 'low') {
        try {
          await configSnapshotService.createSnapshot('pre-remediation');
          logger.info(`Created pre-remediation snapshot for step ${stepOrder}`);
        } catch (error) {
          logger.warn('Failed to create pre-remediation snapshot:', error);
        }
      }

      // Execute the operation intent via device driver
      logger.info(`Executing step ${stepOrder}: ${step.command}`);

      // Dispatch command through DeviceDriverManager or fallback to DevicePool
      const output = await this.executeDeviceCommand(step.command, plan.deviceId, plan.tenantId);

      // Verify the step
      let verificationPassed = true;
      try {
        await this.executeDeviceCommand(step.verification.command, plan.deviceId, plan.tenantId);
        // If verification command succeeds, consider it passed
        // In a real implementation, we'd compare output to expectedResult
      } catch (verifyError) {
        logger.warn(`Verification failed for step ${stepOrder}:`, verifyError);
        verificationPassed = false;
      }

      result = {
        stepOrder,
        success: true,
        output: typeof output === 'string' ? output : JSON.stringify(output),
        duration: Date.now() - startTime,
        verificationPassed,
      };

      // Requirements: critic-reflector 12.1-12.3
      // 调用 CriticService 评估步骤执行结果（如果启用）
      try {
        const { iterationLoop } = await import('./iterationLoop');
        if (iterationLoop.isEnabled()) {
          const { criticService } = await import('./criticService');
          // 使用简化的评估上下文（没有完整的系统指标时）
          const defaultContext = {
            preExecutionState: {
              cpu: { usage: 0 },
              memory: { total: 0, used: 0, free: 0, usage: 0 },
              disk: { total: 0, used: 0, free: 0, usage: 0 },
              uptime: 0,
            },
            postExecutionState: {
              cpu: { usage: 0 },
              memory: { total: 0, used: 0, free: 0, usage: 0 },
              disk: { total: 0, used: 0, free: 0, usage: 0 },
              uptime: 0,
            },
          };
          const evaluation = await criticService.evaluateStep(step, result, defaultContext);
          // 12.2: 将评估结果存储到 ExecutionResult.evaluation 字段
          result.evaluation = evaluation;
          logger.debug(`Step ${stepOrder} evaluated: score=${evaluation.qualityScore}`);
        }
      } catch (evalError) {
        // 评估失败不影响主流程
        logger.debug('Step evaluation skipped or failed:', evalError);
      }

      // Update plan status
      plan.status = 'in_progress';
      await this.savePlan(plan);

      // Log audit
      await auditLogger.log({
        tenantId: plan.tenantId,
        deviceId: plan.deviceId,
        action: 'remediation_execute',
        actor: 'system',
        details: {
          trigger: 'step_executed',
          script: step.command,
          result: result.success ? 'success' : 'failed',
          metadata: {
            planId,
            stepOrder,
            duration: result.duration,
            verificationPassed,
            evaluationScore: result.evaluation?.qualityScore,
          },
        },
      });

    } catch (error) {
      result = {
        stepOrder,
        success: false,
        error: error instanceof Error ? error.message : String(error),
        duration: Date.now() - startTime,
        verificationPassed: false,
      };

      // Log failure
      await auditLogger.log({
        tenantId: plan.tenantId,
        deviceId: plan.deviceId,
        action: 'remediation_execute',
        actor: 'system',
        details: {
          trigger: 'step_failed',
          script: step.command,
          error: result.error,
          metadata: {
            planId,
            stepOrder,
          },
        },
      });
    }

    // Save execution result
    const history = this.executionHistory.get(planId) || [];
    history.push(result);
    this.executionHistory.set(planId, history);
    await this.saveExecutionResults(planId, history);

    // Requirement 7.2, 7.3: 执行完最后一步后检查是否所有步骤完成
    if (result.success) {
      // 获取最新的 plan 状态
      const updatedPlan = await this.getPlan(planId);
      if (updatedPlan) {
        // 检查是否所有步骤都已执行成功
        const executedSteps = history.filter(h => h.success).map(h => h.stepOrder);
        const allStepsExecuted = updatedPlan.steps.every(s => executedSteps.includes(s.order));

        if (allStepsExecuted && updatedPlan.status !== 'completed') {
          updatedPlan.status = 'completed';
          await this.savePlan(updatedPlan);
          logger.info(`All steps completed for plan ${planId}, status updated to completed`);

          // 尝试索引到知识库
          await this.tryIndexPlan(updatedPlan);
        }
      }
    }

    return result;
  }

  /**
   * Execute a device command via DeviceDriverManager (preferred) or DevicePool (legacy fallback)
   *
   * NOTE: Commands use device-agnostic operation intent format (e.g., "query:system/resource").
   * The device driver translates these intents into device-specific commands.
   * Legacy CLI-style commands are still supported via DevicePool fallback
   * for backward compatibility during migration.
   */
  private async executeDeviceCommand(
    command: string,
    deviceId?: string,
    tenantId?: string
  ): Promise<unknown> {
    if (!deviceId) {
      throw new Error('DeviceId is required for remediation execution');
    }

    const cleanCommand = command.trim();

    // Skip comment commands
    if (cleanCommand.startsWith('#')) {
      return 'Skipped comment command';
    }

    // 1. Try DeviceDriverManager first (generalized path)
    const driver = deviceDriverManager.getDriver(deviceId);
    if (driver) {
      return this.executeViaDeviceDriver(driver, cleanCommand);
    }

    // 2. Fallback to legacy DevicePool (backward compatibility)
    logger.debug(`Device ${deviceId} not in DeviceDriverManager, falling back to DevicePool`);
    return this.executeViaDevicePool(cleanCommand, deviceId, tenantId);
  }

  /**
   * Execute command via DeviceDriver (generalized path)
   * Parses operation intent format: "action_type:category/operation [params]"
   */
  private async executeViaDeviceDriver(driver: DeviceDriver, command: string): Promise<unknown> {
    // Parse operation intent: "query:system/resource" → actionType="query:system/resource"
    // The device driver is responsible for interpreting the intent
    const isQuery = command.startsWith('query:');
    const isExecute = command.startsWith('execute:');
    const isConfigure = command.startsWith('configure:');

    if (isQuery) {
      const actionType = command.substring('query:'.length);
      return driver.query(actionType);
    } else if (isExecute) {
      const actionType = command.substring('execute:'.length);
      const result: DeviceExecutionResult = await driver.execute(actionType);
      return result.data;
    } else if (isConfigure) {
      const actionType = command.substring('configure:'.length);
      const result: DeviceExecutionResult = await driver.configure(actionType, {});
      return result.data;
    } else {
      // Unrecognized intent format — pass through as raw execute
      const result: DeviceExecutionResult = await driver.execute(command);
      return result.data;
    }
  }

  /**
   * Legacy fallback: execute via DevicePool (backward-compatible path)
   * Maintained for backward compatibility during migration.
   */
  private async executeViaDevicePool(
    command: string,
    deviceId: string,
    tenantId?: string
  ): Promise<unknown> {
    if (!tenantId) {
      throw new Error('TenantId is required for DevicePool fallback execution');
    }

    const devicePool = await getServiceAsync<DevicePool>(SERVICE_NAMES.DEVICE_POOL);
    const client = await devicePool.getConnection(tenantId, deviceId);

    if (!client) {
      throw new Error(`No available device client for device ${deviceId}`);
    }

    if (!client.isConnected()) {
      throw new Error(`Device client for device ${deviceId} is not connected`);
    }

    // Handle print/query commands
    if (command.includes('/print')) {
      const basePath = command.replace('/print', '').replace(/\s+.*$/, '');
      return await client.print(basePath);
    }

    // Handle other commands via raw execution
    return await client.executeRaw(command);
  }


  /**
   * Execute all auto-executable steps
   * Requirement 7.1: 执行整个方案（仅自动执行步骤）
   */
  async executeAutoSteps(planId: string): Promise<ExecutionResult[]> {
    await this.initialize();

    const plan = await this.getPlan(planId);
    if (!plan) {
      throw new Error(`Plan not found: ${planId}`);
    }

    // Filter auto-executable steps
    const autoSteps = plan.steps.filter(s => s.autoExecutable);

    if (autoSteps.length === 0) {
      logger.info(`No auto-executable steps in plan ${planId}`);
      return [];
    }

    const results: ExecutionResult[] = [];

    // Update plan status
    plan.status = 'in_progress';
    await this.savePlan(plan);

    // Execute steps in order
    for (const step of autoSteps) {
      const result = await this.executeStep(planId, step.order);
      results.push(result);

      // Stop on failure
      if (!result.success) {
        logger.warn(`Auto-execution stopped at step ${step.order} due to failure`);
        plan.status = 'failed';
        await this.savePlan(plan);
        break;
      }
    }

    // Check if all steps completed successfully
    const allSucceeded = results.every(r => r.success);
    const allStepsExecuted = results.length === autoSteps.length;

    if (allSucceeded && allStepsExecuted) {
      // Check if there are non-auto steps remaining
      const hasManualSteps = plan.steps.some(s => !s.autoExecutable);
      if (!hasManualSteps) {
        plan.status = 'completed';
        await this.savePlan(plan);

        // Active Self-Healing: Learn from successful remediation (Requirement: Phase 3)
        if (plan.description) {
          // Fire and forget (don't block)
          ruleEvolutionService.learnFromSuccessfulRemediation(plan, plan.description)
            .catch(err => logger.error('Failed to invoke rule evolution learning:', err));
        }

        // 使用 tryIndexPlan 索引到知识库 (Requirements: 7.1-7.4, 8.1-8.3)
        await this.tryIndexPlan(plan);
      }
      // If there are manual steps, keep status as in_progress
    }

    await this.savePlan(plan);

    logger.info(`Executed ${results.length} auto steps for plan ${planId}, success: ${allSucceeded}`);
    return results;
  }

  /**
   * Execute rollback
   * Requirement 7.4: 生成对应的回滚方案
   */
  async executeRollback(planId: string): Promise<ExecutionResult[]> {
    await this.initialize();

    const plan = await this.getPlan(planId);
    if (!plan) {
      throw new Error(`Plan not found: ${planId}`);
    }

    if (plan.rollback.length === 0) {
      logger.info(`No rollback steps in plan ${planId}`);
      return [];
    }

    const results: ExecutionResult[] = [];

    // Log rollback start
    await auditLogger.log({
      tenantId: plan.tenantId,
      deviceId: plan.deviceId,
      action: 'remediation_execute',
      actor: 'system',
      details: {
        trigger: 'rollback_started',
        metadata: {
          planId,
          rollbackSteps: plan.rollback.length,
        },
      },
    });

    // Execute rollback steps in order
    for (const step of plan.rollback) {
      const startTime = Date.now();

      try {
        // Skip comment commands
        if (step.command.startsWith('#')) {
          results.push({
            stepOrder: step.order,
            success: true,
            output: 'Skipped (comment)',
            duration: 0,
          });
          continue;
        }

        const output = await this.executeDeviceCommand(step.command, plan.deviceId, plan.tenantId);

        results.push({
          stepOrder: step.order,
          success: true,
          output: typeof output === 'string' ? output : JSON.stringify(output),
          duration: Date.now() - startTime,
        });
      } catch (error) {
        results.push({
          stepOrder: step.order,
          success: false,
          error: error instanceof Error ? error.message : String(error),
          duration: Date.now() - startTime,
        });

        // Continue with other rollback steps even on failure
        logger.warn(`Rollback step ${step.order} failed:`, error);
      }
    }

    // Update plan status
    plan.status = 'rolled_back';
    await this.savePlan(plan);

    // Log rollback completion
    const allSucceeded = results.every(r => r.success);
    await auditLogger.log({
      tenantId: plan.tenantId,
      deviceId: plan.deviceId,
      action: 'remediation_execute',
      actor: 'system',
      details: {
        trigger: 'rollback_completed',
        result: allSucceeded ? 'success' : 'partial_failure',
        metadata: {
          planId,
          successCount: results.filter(r => r.success).length,
          failureCount: results.filter(r => !r.success).length,
        },
      },
    });

    logger.info(`Executed rollback for plan ${planId}, success: ${allSucceeded}`);
    return results;
  }

  /**
   * Get plan by ID
   */
  async getPlan(planId: string): Promise<RemediationPlan | null> {
    await this.initialize();

    // Check cache first
    if (this.plansCache.has(planId)) {
      return this.plansCache.get(planId)!;
    }

    // Try to load from disk
    try {
      const filePath = path.join(PLANS_DIR, `${planId}.json`);
      const content = await fs.readFile(filePath, 'utf-8');
      const plan = JSON.parse(content) as RemediationPlan;
      this.plansCache.set(planId, plan);
      return plan;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return null;
      }
      logger.error(`Failed to load plan ${planId}:`, error);
      return null;
    }
  }

  /**
   * Get execution history for a plan
   */
  async getExecutionHistory(planId: string): Promise<ExecutionResult[]> {
    await this.initialize();

    // Check memory cache first
    if (this.executionHistory.has(planId)) {
      return this.executionHistory.get(planId)!;
    }

    // Try to load from disk (search recent files)
    const results: ExecutionResult[] = [];
    const now = Date.now();
    const sevenDaysAgo = now - 7 * 24 * 60 * 60 * 1000;

    try {
      const files = await fs.readdir(EXECUTIONS_DIR);
      for (const file of files) {
        if (!file.endsWith('.json')) continue;

        try {
          const content = await fs.readFile(path.join(EXECUTIONS_DIR, file), 'utf-8');
          const executions = JSON.parse(content) as Array<{
            planId: string;
            timestamp: number;
            results: ExecutionResult[];
          }>;

          for (const exec of executions) {
            if (exec.planId === planId && exec.timestamp >= sevenDaysAgo) {
              results.push(...exec.results);
            }
          }
        } catch (error) {
          logger.debug(`Failed to read execution file ${file}:`, error);
        }
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        logger.error('Failed to read execution history:', error);
      }
    }

    // Cache the results
    if (results.length > 0) {
      this.executionHistory.set(planId, results);
    }

    return results;
  }

  /**
   * Get all plans (for listing)
   */
  async getPlans(limit: number = 50): Promise<RemediationPlan[]> {
    await this.initialize();

    const plans = Array.from(this.plansCache.values());

    // Sort by timestamp descending
    plans.sort((a, b) => b.timestamp - a.timestamp);

    return plans.slice(0, limit);
  }

  /**
   * Get plans by alert ID
   */
  async getPlansByAlertId(alertId: string): Promise<RemediationPlan[]> {
    await this.initialize();

    const plans = Array.from(this.plansCache.values())
      .filter(p => p.alertId === alertId)
      .sort((a, b) => b.timestamp - a.timestamp);

    return plans;
  }

  /**
   * Update plan status
   * Requirement 7.1: 状态更新为 completed 时调用索引
   */
  async updatePlanStatus(planId: string, status: RemediationPlan['status']): Promise<void> {
    const plan = await this.getPlan(planId);
    if (!plan) {
      throw new Error(`Plan not found: ${planId}`);
    }

    plan.status = status;
    await this.savePlan(plan);

    logger.info(`Updated plan ${planId} status to ${status}`);

    // Requirement 7.1: 状态变为 completed 时尝试索引
    if (status === 'completed') {
      await this.tryIndexPlan(plan);
    }
  }

  /**
   * Delete a plan
   */
  async deletePlan(planId: string): Promise<void> {
    await this.initialize();

    const filePath = path.join(PLANS_DIR, `${planId}.json`);

    try {
      await fs.unlink(filePath);
      this.plansCache.delete(planId);
      this.executionHistory.delete(planId);
      logger.info(`Deleted plan ${planId}`);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }
  }
}

// Export singleton instance
export const remediationAdvisor = new RemediationAdvisor();
